/****** Script do comando SelectTopNRows de SSMS  ******/

USE easycollector 

DROP TABLE #BASE 
SELECT 
	   [COD_ASSESSORIA]
      ,[PERIODO] 
	  ,replace(CONVERT(VARCHAR(10), primeiro_login, 104) + ' ' + CONVERT(VARCHAR(8), primeiro_login, 108),'.','-') AS PRIMEIRO_LOGIN 
      ,replace(CONVERT(VARCHAR(10), ULTIMO_LOGOUT, 104) + ' ' + CONVERT(VARCHAR(8), ULTIMO_LOGOUT, 108),'.','-') AS ULTIMO_LOGOUT 
      ,[USUARIO]
      ,[REGIME]
      ,DATA_ADMISSAO = CAST(DATA_ADMISSAO AS DATE) 
      ,CARGA_HORARIA = CONVERT(NVARCHAR,CARGA_HORARIA,108)
      ,TTL = CONVERT(NVARCHAR,[TTL],108)
      ,TTD = CONVERT(NVARCHAR,[TTD],108)
      ,TTPNR = CONVERT(NVARCHAR,[TTPNR],108)
      ,TTPE = CONVERT(NVARCHAR,[TTPE],108)
      ,TTT = CONVERT(NVARCHAR,[TTT],108)
      ,TTA = CONVERT(NVARCHAR,[TTA],108)
      ,TMD = CONVERT(NVARCHAR,TMD,108)
      ,TMT = CONVERT(NVARCHAR,[TMT],108)
      ,TMA = CONVERT(NVARCHAR,[TMA],108)
      ,[ATENDIDAS ATIVO]
      ,[ATENDIDAS RECEPTIVO]
INTO #BASE 
FROM [easycollector].[dbo].TB_RENNER_EXPORTA_ANDRE_0706 



SELECT 
	  *
FROM		#BASE 
WHERE COD_ASSESSORIA IS NOT NULL 



